[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148] mod_wsgi (pid=1867): Exception occurred processing WSGI script '/home/ec2-user/CouchbaseCloud/CouchbaseCloud/CouchbaseCloud/wsgi.py'.
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148] Traceback (most recent call last):
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]     self.load_middleware()
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 44, in load_middleware
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 54, in __getattr__
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]     self._setup(name)
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 49, in _setup
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]     self._wrapped = Settings(settings_module)
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 132, in __init__
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148]     % (self.SETTINGS_MODULE, e)
[Wed Aug 06 13:03:20 2014] [error] [client 10.17.46.148] ImportError: Could not import settings 'CouchbaseCloud.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named CouchbaseCloud.settings
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148] mod_wsgi (pid=1946): Exception occurred processing WSGI script '/home/ec2-user/CouchbaseCloud/CouchbaseCloud/CouchbaseCloud/wsgi.py'.
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148] Traceback (most recent call last):
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]     self.load_middleware()
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 44, in load_middleware
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 54, in __getattr__
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]     self._setup(name)
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 49, in _setup
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]     self._wrapped = Settings(settings_module)
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 132, in __init__
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148]     % (self.SETTINGS_MODULE, e)
[Wed Aug 06 13:04:03 2014] [error] [client 10.17.46.148] ImportError: Could not import settings 'CouchbaseCloud.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named CouchbaseCloud.settings
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148] mod_wsgi (pid=1948): Exception occurred processing WSGI script '/home/ec2-user/CouchbaseCloud/CouchbaseCloud/CouchbaseCloud/wsgi.py'.
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148] Traceback (most recent call last):
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]     self.load_middleware()
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/core/handlers/base.py", line 44, in load_middleware
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]     for middleware_path in settings.MIDDLEWARE_CLASSES:
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 54, in __getattr__
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]     self._setup(name)
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 49, in _setup
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]     self._wrapped = Settings(settings_module)
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]   File "/usr/lib/python2.6/site-packages/django/conf/__init__.py", line 132, in __init__
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148]     % (self.SETTINGS_MODULE, e)
[Wed Aug 06 13:04:15 2014] [error] [client 10.17.46.148] ImportError: Could not import settings 'CouchbaseCloud.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named CouchbaseCloud.settings
